# travis build script for ts-logging
language: node_js

node_js:
  - "6"

install:
  - npm install

script:
  - npm run test-build
  - npm run build

deploy:
  provider: npm
  email: sebastian@gingter.org
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master
